services:
  - type: web
    name: simats-aqua-backend
    env: python
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.1
      - key: API_SECRET_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: FIREBASE_KEY_JSON
        sync: false
    healthCheckPath: /api/health
